# fly.toml app configuration file generated for red-thunder-3074 on 2023-07-14T20:43:06Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "red-thunder-3074"
primary_region = "ord"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
